### ISSUE TITLE
Validation datasets

### ISSUE THREAD

**Issue by FFinotello** [omnideconv/deconvBench#20]
Hi, @mlist and @grst!

We should decide how to save and (at some point) publish the validation datasets put together as they can be very helpful for the deconvolution community.
This will include real bulk datasets (RNA-seq TPM and counts + FACS cell fractions) from human an mouse; the latter would be relevant also for the [mouse-immundeconv vignette](https://github.com/icbi-lab/immunedeconv/issues/93). All except one dataset are ready and the authors agreed on their publication.
We will also have several, simulated pseudobulk datasets that we might want to save online but publish only at a later stage.

What could be the best scheme for storing such data having some flexibility on what could be integrated or made public at a later stage? Whatever scheme we chose, it would be nice to reference it in the omnideconv website in a "validation data" section.

Tagging also @LorenzoMerotto and @alex-d13 

Cheers,
Francesca

**Comment by SciLiciumTheo** [comment]
Hello,

I would be very much interested in this.
The issue is marked as completed, was it implemented or not?

Cheers,
Theo
